In [1]:
#Creating 1D array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# 2D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [14]:
# creating some arrays that contains by default values

arr_zeros = np.zeros((3,3))
print("The array with zeros as default values : \n",arr_zeros)

arr_ones = np.ones((2,3))
print("The array with ones as default values : \n",arr_ones)

arr_desired = np.full((2,2,), "7")
print("The array with desired number as default value : \n",arr_desired)

arr_iden = np.eye(3)
print("The identity matrix of any dimension : \n",arr_iden)

arr_range = np.arange(1,10,2)
print("Printing an array of desired range : \n",arr_range)

The array with zeros as default values : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
The array with ones as default values : 
 [[1. 1. 1.]
 [1. 1. 1.]]
The array with desired number as default value : 
 [['7' '7']
 ['7' '7']]
The identity matrix of any dimension : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Printing an array of desired range : 
 [1 3 5 7 9]


In [15]:
#checking properties of an array

arr = np.array([[1,2,3,4,5,6],
                [7,8,9,10,11,12]])

print("The shape of array is :",arr.shape)
print("The number of elements in array is :",arr.size)
print("The dimension of array is :",arr.ndim)
print("The data type of elements stored in array is :",arr.dtype)

The shape of array is : (2, 6)
The number of elements in array is : 12
The dimension of array is : 2
The data type of elements stored in array is : int32


In [ ]:
# changing the properties of an array
arr = np.array([[1,2,3,4,5,6],
                [7,8,9,10,11,12]])
arr2 = arr.reshape((4,3))
print("The reshaped array is :\n",arr2)

arr3 = arr.astype(float)        #change the data type of elements in array
print("New array with changed data type :\n",arr3)

The reshaped array is :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
New array with changed data type :
 [[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]]


In [24]:
# applying mathematical operations on the array

arr = np.arange(10,100,10)
print(arr + 10)         #add 10 to all elemnts of the array
print(arr - 5)          #subtract 5 from all elements
print(arr * 2)
print(arr ** 2)
print(arr / 2)
print(arr // 2)
print(arr % 2)

[ 20  30  40  50  60  70  80  90 100]
[ 5 15 25 35 45 55 65 75 85]
[ 20  40  60  80 100 120 140 160 180]
[ 100  400  900 1600 2500 3600 4900 6400 8100]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]
[ 5 10 15 20 25 30 35 40 45]
[0 0 0 0 0 0 0 0 0]


In [27]:
# aggregation function on array
# to summarise the content of the array

arr = np.arange(10,20,1)
print("The original array is : ",arr)
print("Sum is ->",np.sum(arr))
print("Mean is ->",np.mean(arr))
print("Max element is ->",np.max(arr))
print("Min element is ->",np.min(arr))
print("Standard deviation is ->",np.std(arr))
print("Variance is ->",np.var(arr))


The original array is :  [10 11 12 13 14 15 16 17 18 19]
Sum is -> 145
Mean is -> 14.5
Max element is -> 19
Min element is -> 10
Standard deviation is -> 2.8722813232690143
Variance is -> 8.25


#### Indexing and Slicing

In [33]:
# Normal Indexing
arr = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr[1,2])         
print(arr[0,2])
print(arr[2,2])
print(arr[1,0])

6
3
9
4


In [ ]:
# fancy indexing --> selecting multiple non sequential elements from an array
arr = np.arange(10,100,5)
print("Original array : ",arr)
print(arr[[1,5,7,10,4,7]])    #accessing mutliple elements at a time

Original array :  [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[15 35 45 60 30 45]


In [ ]:
# boolean masking --> to choose only those elements from array which satisfies a specific condition

arr = np.arange(10,100,3)
print("Original array : ",arr)
print(arr[arr % 4 == 0])

Original array :  [10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88 91 94 97]
[16 28 40 52 64 76 88]
