In [2]:
#Creating 1D array
import numpy as np
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [3]:
# 2D array
arr = np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.ndim)

[[1 2 3]
 [4 5 6]]
2


In [3]:
# creating some arrays that contains by default values

arr_zeros = np.zeros((3,3))
print("The array with zeros as default values : \n",arr_zeros)

arr_ones = np.ones((2,3))
print("The array with ones as default values : \n",arr_ones)

arr_desired = np.full((2,2,), "7")
print("The array with desired number as default value : \n",arr_desired)

arr_iden = np.eye(3)
print("The identity matrix of any dimension : \n",arr_iden)

arr_range = np.arange(1,10,2)
print("Printing an array of desired range : \n",arr_range)

The array with zeros as default values : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
The array with ones as default values : 
 [[1. 1. 1.]
 [1. 1. 1.]]
The array with desired number as default value : 
 [['7' '7']
 ['7' '7']]
The identity matrix of any dimension : 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Printing an array of desired range : 
 [1 3 5 7 9]


In [15]:
#checking properties of an array

arr = np.array([[1,2,3,4,5,6],
                [7,8,9,10,11,12]])

print("The shape of array is :",arr.shape)
print("The number of elements in array is :",arr.size)
print("The dimension of array is :",arr.ndim)
print("The data type of elements stored in array is :",arr.dtype)

The shape of array is : (2, 6)
The number of elements in array is : 12
The dimension of array is : 2
The data type of elements stored in array is : int32


In [ ]:
# changing the properties of an array
import numpy as np
arr = np.array([[1,2,3,4,5,6],
                [7,8,9,10,11,12]])
arr2 = arr.reshape((4,3))                     #creates only view
print("The reshaped array is :\n",arr2)     
print(arr)         #original array remains same

arr3 = arr.astype(float)        #change the data type of elements in array
print("New array with changed data type :\n",arr3)

#converting the multidimensional array in 1D array
print("The converted 1D array is :\n",arr.ravel())              #creates a copy
print("The converted 1D array is :\n",arr.flatten())            #creates a view

The reshaped array is :
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
New array with changed data type :
 [[ 1.  2.  3.  4.  5.  6.]
 [ 7.  8.  9. 10. 11. 12.]]
The converted 1D array is :
 [ 1  2  3  4  5  6  7  8  9 10 11 12]
The converted 1D array is :
 [ 1  2  3  4  5  6  7  8  9 10 11 12]


In [24]:
# applying mathematical operations on the array

arr = np.arange(10,100,10)
print(arr + 10)         #add 10 to all elemnts of the array
print(arr - 5)          #subtract 5 from all elements
print(arr * 2)
print(arr ** 2)
print(arr / 2)
print(arr // 2)
print(arr % 2)

[ 20  30  40  50  60  70  80  90 100]
[ 5 15 25 35 45 55 65 75 85]
[ 20  40  60  80 100 120 140 160 180]
[ 100  400  900 1600 2500 3600 4900 6400 8100]
[ 5. 10. 15. 20. 25. 30. 35. 40. 45.]
[ 5 10 15 20 25 30 35 40 45]
[0 0 0 0 0 0 0 0 0]


In [27]:
# aggregation function on array
# to summarise the content of the array

arr = np.arange(10,20,1)
print("The original array is : ",arr)
print("Sum is ->",np.sum(arr))
print("Mean is ->",np.mean(arr))
print("Max element is ->",np.max(arr))
print("Min element is ->",np.min(arr))
print("Standard deviation is ->",np.std(arr))
print("Variance is ->",np.var(arr))


The original array is :  [10 11 12 13 14 15 16 17 18 19]
Sum is -> 145
Mean is -> 14.5
Max element is -> 19
Min element is -> 10
Standard deviation is -> 2.8722813232690143
Variance is -> 8.25


#### Indexing and Slicing

In [33]:
# Normal Indexing
arr = np.array([[1,2,3],
                 [4,5,6],
                 [7,8,9]])
print(arr[1,2])         
print(arr[0,2])
print(arr[2,2])
print(arr[1,0])

6
3
9
4


In [ ]:
# fancy indexing --> selecting multiple non sequential elements from an array
arr = np.arange(10,100,5)
print("Original array : ",arr)
print(arr[[1,5,7,10,4,7]])    #accessing mutliple elements at a time

Original array :  [10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[15 35 45 60 30 45]


In [ ]:
# boolean masking --> to choose only those elements from array which satisfies a specific condition

arr = np.arange(10,100,3)
print("Original array : ",arr)
print(arr[arr % 4 == 0])

Original array :  [10 13 16 19 22 25 28 31 34 37 40 43 46 49 52 55 58 61 64 67 70 73 76 79
 82 85 88 91 94 97]
[16 28 40 52 64 76 88]


#### Array Modification
It always creates an new array and the original array remains same, as the array size is fixed always

In [ ]:
# to add new element at specific index --> insert method
import numpy as np
arr = np.array([1,2,3,4,5,6])
new = np.insert(arr,3,10)       #inser 10 at index 3
print(new)

arr_2d = np.array([[1,2,3],
                   [4,5,6]])
new_2d = np.insert(arr_2d,0,[7,8,9],axis=0)   #row wise insert
print(new_2d) 

new_2d = np.insert(arr_2d,2,[7,8],axis=1)     #column wise insert
print(new_2d)

[ 1  2  3 10  4  5  6]
[[7 8 9]
 [1 2 3]
 [4 5 6]]
[[1 2 7 3]
 [4 5 8 6]]


In [ ]:
# to append the element/s at last position of array --> append method
arr = np.array([1,2,3,4,5,6])
new = np.append(arr,10)     #to append only single element  
print(new)
new2 = np.append(arr,[7,8,9])    #to append list of element
print(new2)

[ 1  2  3  4  5  6 10]
[1 2 3 4 5 6 7 8 9]


In [23]:
#to joinbt two arrays --> concatenate method
arr1 = np.arange(1,5)
arr2 = np.arange(5,9)
new_hor = np.concatenate((arr1,arr2),axis=0)    #horizontal stacking
print(new_hor)


[1 2 3 4 5 6 7 8]


In [ ]:
# to delete some specific element
arr = np.arange(1,5)
print(np.delete(arr,2))    #delete the 2 index element

[1 2 4]


In [25]:
#Stacking
#vstack -> to stack two arrays vertically
#hstack -> to stack two arrays horizontally
arr1 = np.arange(1,5)
arr2 = np.arange(5,9)
print(np.vstack((arr1,arr2)))
print(np.hstack((arr1,arr2)))

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [ ]:
#Splitting
arr = np.array([1,2,3,4,5,6])
print(np.split(arr,2))
print(np.hsplit(arr,2))

arr_2d = np.array([[1,2,3], 
               [4,5,6]])
print(np.vsplit(arr_2d,2))     #vsplit only works for multi dimensional array

[array([1, 2, 3]), array([4, 5, 6])]
[array([1, 2, 3]), array([4, 5, 6])]
[array([[1, 2, 3]]), array([[4, 5, 6]])]


#### Handling Missing Values

In [ ]:
#handling the nan values
import numpy as np
arr = np.array([1,2,np.nan,4,np.nan,6])   #define some nan values
print(np.isnan(arr))    #to check any nan value

#to handle these values
print(np.nan_to_num(arr,nan=10))      #replace the nan values by 10


[False False  True False  True False]
[ 1.  2. 10.  4. 10.  6.]


In [37]:
#handling the infinite values
import numpy as np
arr = np.array([1,2,np.inf,4,-np.inf,6])  #define infinite values(positive and negative)
print(np.isinf(arr))        #to check infinite values


#to handle these values
print(np.nan_to_num(arr,posinf=100,neginf=-100))

[False False  True False  True False]
[   1.    2.  100.    4. -100.    6.]
